// =============================================================
// AgentBus types — arXiv 2604.07988 §3
// =============================================================

/** The type tag for each entry appended to the AgentBus. */
export enum PayloadType {
  /** Inference input fed to the LLM (user message / prior result). */
  InfIn = 'InfIn',
  /** Inference output produced by the LLM (raw model response). */
  InfOut = 'InfOut',
  /** Extracted intended action proposed by the Driver. */
  Intent = 'Intent',
  /** Vote cast by a Voter on a pending intent. */
  Vote = 'Vote',
  /** Commit decision emitted by the Decider. */
  Commit = 'Commit',
  /** Abort decision emitted by the Decider. */
  Abort = 'Abort',
  /** Action result produced by the Executor after execution. */
  Result = 'Result',
  /** Mailbox message from an external user or agent. */
  Mail = 'Mail',
  /** Policy change entry controlling voter/decider behaviour. */
  Policy = 'Policy',
}

// ----- Concrete payload shapes -----------------------------------

export type InfInPayload = {
  type: PayloadType.InfIn;
  messages: Array<{ role: 'user' | 'assistant' | 'system'; content: string }>;
};

export type InfOutPayload = {
  type: PayloadType.InfOut;
  text: string;
};

export type IntentPayload = {
  type: PayloadType.Intent;
  /** Unique correlation id, used to match votes / commit / abort back to this intent. */
  intentId: string;
  /** The action code / description as emitted by the Driver. */
  action: string;
};

export type VotePayload = {
  type: PayloadType.Vote;
  intentId: string;
  voterId: string;
  /** true = approve, false = reject. */
  approve: boolean;
  reason?: string;
};

export type CommitPayload = {
  type: PayloadType.Commit;
  intentId: string;
};

export type AbortPayload = {
  type: PayloadType.Abort;
  intentId: string;
  reason?: string;
};

export type ResultPayload = {
  type: PayloadType.Result;
  intentId: string;
  output: string;
  error?: string;
};

export type MailPayload = {
  type: PayloadType.Mail;
  from: string;
  content: string;
};

export type PolicyPayload = {
  type: PayloadType.Policy;
  /** Which policy domain this update targets (e.g. 'quorum', 'voter:<id>'). */
  target: string;
  value: unknown;
};

export type Payload =
  | InfInPayload
  | InfOutPayload
  | IntentPayload
  | VotePayload
  | CommitPayload
  | AbortPayload
  | ResultPayload
  | MailPayload
  | PolicyPayload;

/** A single stamped entry in the AgentBus. */
export type Entry = {
  /** Monotonically increasing log position (0-based). */
  position: number;
  /** Wall-clock timestamp (ms since epoch). */
  realtimeTs: number;
  payload: Payload;
};

// ----- Quorum policy ----------------------------------------------

export enum QuorumPolicy {
  /** Commit immediately without any votes. */
  OnByDefault = 'on_by_default',
  /** Commit as soon as the first vote is received (approve or reject). */
  FirstVoter = 'first_voter',
  /** Commit only when ALL registered voters approve (any reject → abort). */
  BooleanAnd = 'boolean_and',
  /** Commit when at least one voter approves; abort only if all reject. */
  BooleanOr = 'boolean_or',
}

// ----- Component classification -----------------------------------

/**
 * Component isolation tier from §3.1.
 * - Classic: no LLM contact.
 * - LLMPassive: sends/receives text strings to LLMs; never executes generated code.
 * - LLMActive: executes code generated by LLMs (Executor only).
 */
export type ComponentTier = 'classic' | 'llm-passive' | 'llm-active';

// ----- AgentBus interface -----------------------------------------

/** The public API of an AgentBus (shared log). */
export interface IAgentBus {
  /** Durably append a payload; returns the log position of the new entry. */
  append(payload: Payload): Promise<number>;
  /** Read all entries whose position falls in [start, end). */
  read(start: number, end: number): Promise<Entry[]>;
  /** Return the current tail position (exclusive upper bound). */
  tail(): Promise<number>;
  /**
   * Blocking poll: resolves with newly arrived entries whose payload
   * type is in `filter` and whose position >= `start`.
   * Polls until at least one matching entry is available.
   */
  poll(start: number, filter: PayloadType[]): Promise<Entry[]>;
}

// ----- Voter interface --------------------------------------------

export interface IVoter {
  readonly id: string;
  readonly tier: ComponentTier;
  /**
   * Evaluate an intent and return a VotePayload.
   * Voters may inspect the AgentBus for context (introspection).
   */
  vote(intent: IntentPayload, bus: IAgentBus): Promise<VotePayload>;
}

// ----- Executor interface -----------------------------------------

export interface IExecutor {
  readonly tier: ComponentTier;
  /**
   * Execute the committed action and return a result string.
   * May throw — the outer Executor component will catch and record the error.
   */
  execute(action: string): Promise<string>;
}

// ----- Driver LLM interface ---------------------------------------

/**
 * The inference layer used by the Driver.
 * Accepts a list of messages and returns the raw model output text.
 */
export interface IInferenceClient {
  infer(
    messages: Array<{ role: 'user' | 'assistant' | 'system'; content: string }>,
  ): Promise<string>;
}

// ----- LogActAgent options ----------------------------------------

export type LogActAgentOptions = {
  bus: IAgentBus;
  inferenceClient: IInferenceClient;
  voters?: IVoter[];
  executor?: IExecutor;
  quorumPolicy?: QuorumPolicy;
  /**
   * Maximum number of agentic turns before the agent stops.
   * Useful for tests and bounded tasks. Default: Infinity.
   */
  maxTurns?: number;
};
